version: "3"
services:

  web:
    # 将 username/repo:tag 替换为您的名称和镜像详细信息
    image: zf0719/get-started:part1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:
